import { SignIn, SignInButton, SignUpButton, UserButton, useUser } from "@clerk/nextjs";
import { log } from "console";
import { type NextPage } from "next";
import Head from "next/head";
import dayjs from "dayjs";
import relativeTime from 'dayjs/plugin/relativeTime';
import Link from "next/link";

import { api } from "~/utils/api";

dayjs.extend(relativeTime);

const Home: NextPage = () => {

  const user = useUser();

  
  const {data} = api.posts.getAll.useQuery();
  console.log(user.user?.profileImageUrl);

  const imgURL = user.user?.profileImageUrl;
 

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">


        
<nav className=" bg-slate-200 dark:bg-gray-1200">
    <div className="flex flex-wrap justify-between items-center mx-auto max-w-screen-xl p-4 bg-slate-200">
            <span className="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">JudoBet</span>
                <div className="flex items-center">
            <a href="#" className="text-sm  text-blue-600 dark:text-blue-500 hover:underline">
              {!user.isSignedIn&&<SignInButton />}
              {!!user.isSignedIn&&<UserButton/>}
              <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" />
              </a>
        </div>
    </div>
</nav>
<nav className="bg-gray-100 dark:bg-gray-700">
    <div className="max-w-screen-xl px-4 py-3 mx-auto">
        <div className="flex items-center">
            <ul className="flex flex-row font-medium mt-0 mr-6 space-x-8 text-sm">
                <li>
                    <a href="#" className="text-gray-900 dark:text-white hover:underline" aria-current="page">Home</a>
                </li>
                <li>
                    <a href="#" className="text-gray-900 dark:text-white hover:underline">Tournaments</a>
                </li>
                <li>
                    <a href="#" className="text-gray-900 dark:text-white hover:underline">My Bets</a>
                </li>
                <li>
                    <a href="#" className="text-gray-900 dark:text-white hover:underline">Team</a>
                </li>
            </ul>
        </div>
    </div>
</nav>



       
     
        
        <div className="justify-between items-center mx-auto max-w-screen-xl p-4 bg-slate-20">
          {data?.map((post) =>(<p key={post.id}>{post.bet1}</p>
          ))}
        
        <p>footer</p>
        </div>


      </main>
    </>
  );
};

export default Home;
